name       : libcap2
version    : '2.27'
release    : 8
source     :
    - https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.27.tar.xz : dac1792d0118bee6aae6ba7fb93ff1602c6a9bda812fd63916eee1435b9c486a
license    : GPL-2.0-or-later
component  : system.base
summary    : User-space interfaces to the POSIX 1003.1e capabilities available in Linux kernels
description: |
    user-space interfaces to the POSIX 1003.1e capabilities available in Linux kernels
emul32     : yes
builddeps  :
    - pkgconfig32(libattr)
    - pam-32bit-devel
build      : |
    %make CC="$CC"
install    : |
    %make_install RAISE_SETFCAP=no lib=lib%LIBSUFFIX% prefix=/usr CC="$CC"

    if [[ ! -z "${EMUL32BUILD}" ]]; then
        rm $installdir/%libdir%/security -rf
    else
        mkdir $installdir/lib
        mv $installdir/%libdir%/security $installdir/lib/.
    fi

    # no static, thanks.
    rm $installdir/%libdir%/*.a -v
