name       : libcap2
version    : 2.25
release    : 6
source     :
    - https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.25.tar.xz : 693c8ac51e983ee678205571ef272439d83afe62dd8e424ea14ad9790bc35162
license    :
    - GPL-2.0
summary    : User-space interfaces to the POSIX 1003.1e capabilities available in Linux kernels
emul32     : yes
component  : system.base
builddeps  :
    - attr-devel
    - attr-32bit-devel
    - pam-32bit-devel
description: |
    user-space interfaces to the POSIX 1003.1e capabilities available in Linux kernels
build      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %make CC="gcc -m32"
    else
        %make
    fi
install    : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %make_install RAISE_SETFCAP=no lib=lib32 prefix=/usr CC="gcc -m32"
        rm $installdir/%libdir%/security -rf
        # no static, thanks.
        rm $installdir/%libdir%/*.a -v
    else
        %make_install RAISE_SETFCAP=no lib=lib64 prefix=/usr
        mkdir $installdir/lib
        mv $installdir/%libdir%/security $installdir/lib/.
        # no static, thanks.
        rm $installdir/%libdir%/*.a -v
    fi
    %make clean
