name        : libcap2
version     : 2.22
release     : 5
source      :
    - http://ftp.de.debian.org/debian/pool/main/libc/libcap2/libcap2_2.22.orig.tar.gz : e1cae65d8febf2579be37c255d2e058715785ead481a4e6a4357a06aff84721f
license     :
    - GPL-2.0
summary     : User-space interfaces to the POSIX 1003.1e capabilities available in Linux kernels
emul32      : yes
builddeps   :
    - glibc-32bit-devel
    - libgcc-32bit
    - attr-devel
    - attr-32bit-devel
    - pam-32bit-devel
description : |
    user-space interfaces to the POSIX 1003.1e capabilities available in Linux kernels
build      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %make CC="gcc -m32"
    else
        %make
    fi
install    : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %make_install RAISE_SETFCAP=no lib=lib32 prefix=/usr CC="gcc -m32"
        rm $installdir/%libdir%/security -rf
        # no static, thanks.
        rm $installdir/%libdir%/*.a -v
    else
        %make_install RAISE_SETFCAP=no lib=lib64 prefix=/usr
        mkdir $installdir/lib
        mv $installdir/%libdir%/security $installdir/lib/.
        # no static, thanks.
        rm $installdir/%libdir%/*.a -v
    fi
    %make clean
