name        : libcap2
version     : 2.22
release     : 3
source      :
    - http://ftp.de.debian.org/debian/pool/main/libc/libcap2/libcap2_2.22.orig.tar.gz : e1cae65d8febf2579be37c255d2e058715785ead481a4e6a4357a06aff84721f
license     :
    - GPL-2.0
summary     : User-space interfaces to the POSIX 1003.1e capabilities available in Linux kernels
description : |
    user-space interfaces to the POSIX 1003.1e capabilities available in Linux kernels
build      : |
    %make
install    : |
    %make_install RAISE_SETFCAP=no lib=lib64 prefix=/usr
    mkdir $installdir/lib
    mv $installdir/%libdir%/security $installdir/lib/.
    # no static, thanks.
    rm $installdir/%libdir%/*.a -v
