name       : libcap2
version    : 2.26
release    : 7
source     :
    - https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.26.tar.xz : b630b7c484271b3ba867680d6a14b10a86cfa67247a14631b14c06731d5a458b
license    : GPL-2.0-or-later
component  : system.base
summary    : User-space interfaces to the POSIX 1003.1e capabilities available in Linux kernels
description: |
    user-space interfaces to the POSIX 1003.1e capabilities available in Linux kernels
emul32     : yes
builddeps  :
    - pkgconfig32(libattr)
    - pam-32bit-devel
build      : |
    %make CC="$CC"
install    : |
    %make_install RAISE_SETFCAP=no lib=lib%LIBSUFFIX% prefix=/usr CC="$CC"

    if [[ ! -z "${EMUL32BUILD}" ]]; then
        rm $installdir/%libdir%/security -rf
    else
        mkdir $installdir/lib
        mv $installdir/%libdir%/security $installdir/lib/.
    fi

    # no static, thanks.
    rm $installdir/%libdir%/*.a -v
